spring.application.name=seminare
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.mvc.problemdetails.enabled=true
spring.main.banner-mode=off
